version: '3'

services:
  node-task-manager:
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      MongoURI: mongodb://mongo:27017/task-manager
    ports:
      - 3000:3000
    command: npm run dev

  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
    volumes:
      - ./data/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo